### ISSUE TITLE
Minor improvement

### ISSUE THREAD

**Issue by Nyholm** [ikoene/marvel-api-bundle#1]
Instead of adding parameters to your kernel like: 
https://github.com/ikoene/marvel-api-bundle/blob/master/DependencyInjection/IkoeneMarvelApiExtension.php#L22

You could get the definition and replace the arguments with your config. 

```php
$container->getDefinition('ikoene_marvel_api_client')
  ->replaceArgument(0, $config['public_api_key'])
  ->replaceArgument(1, $config['private_api_key']);
```

**Comment by ikoene** [comment]
Thanks, I didn’t knew about that!

Is this considered a better way of adding parameters to services?

**Comment by Nyholm** [comment]
Yes, I would say so. There is no reason for adding parameter to your container when you can add them directly to the service.
